export interface Family {
    en: string,
    zhs: string,
    zhs_rm: string,
    zht: string,
    zht_rm: string,
    ja: string,
    ja_rm:  string,
    ko: string,
    es: string,
    fr: string,
    ru: string,
    th: string,
    vi: string,
    de: string,
    id: string,
    pt: string,
    tr: string,
    it: string,
}